// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQugYZv54yn15_w58SXGXsSIfq0GUxxc',
    appId: '1:222929962466:web:0eef134e2ebc52a8cc25bb',
    messagingSenderId: '222929962466',
    projectId: 'chat-app-bfcc7',
    authDomain: 'chat-app-bfcc7.firebaseapp.com',
    storageBucket: 'chat-app-bfcc7.firebasestorage.app',
    measurementId: 'G-FRPYES0HB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOVvqHoUS2cnFP7zfgDGGkOHOAaQNy46U',
    appId: '1:222929962466:android:4ff530c469a09e5acc25bb',
    messagingSenderId: '222929962466',
    projectId: 'chat-app-bfcc7',
    storageBucket: 'chat-app-bfcc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZcSuflKGdWA2QmbhqsocY0obd2YBlr0Q',
    appId: '1:222929962466:ios:ee143232aaa0224ccc25bb',
    messagingSenderId: '222929962466',
    projectId: 'chat-app-bfcc7',
    storageBucket: 'chat-app-bfcc7.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZcSuflKGdWA2QmbhqsocY0obd2YBlr0Q',
    appId: '1:222929962466:ios:ee143232aaa0224ccc25bb',
    messagingSenderId: '222929962466',
    projectId: 'chat-app-bfcc7',
    storageBucket: 'chat-app-bfcc7.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOQugYZv54yn15_w58SXGXsSIfq0GUxxc',
    appId: '1:222929962466:web:83c987428b6efd4acc25bb',
    messagingSenderId: '222929962466',
    projectId: 'chat-app-bfcc7',
    authDomain: 'chat-app-bfcc7.firebaseapp.com',
    storageBucket: 'chat-app-bfcc7.firebasestorage.app',
    measurementId: 'G-6EZWG7XG1S',
  );
}
